[package]
name = "stow"
version = "0.1.0"
edition = "2021"
description = "un/symlink pakages from the STOW_DIR to the target directory"

[dependencies]
clap = { version = "4.3.1", features = ["derive", "env"] }
uuid = { version = "1.3.2", features = ["v4"] }
walkdir = "2.3.3"
