[package]
name = "stow"
version = "0.1.0"
edition = "2021"
description = "un/symlink pakages from the STOW_DIR to the target directory"

[dependencies]
clap = { version = "4.1.11", features = ["derive", "env"] }
uuid = { version = "1.2.1", features = ["v4"] }
walkdir = "2.3.2"
